/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HoldrArtistsERC1155 } from "./HoldrArtistsERC1155";
export type { HoldrArtistsERC1155UpgradeTest } from "./HoldrArtistsERC1155UpgradeTest";
export type { HoldrProxy } from "./HoldrProxy";
