/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HoldrArtistsERC1155__factory } from "./HoldrArtistsERC1155__factory";
export { HoldrArtistsERC1155UpgradeTest__factory } from "./HoldrArtistsERC1155UpgradeTest__factory";
